const CACHE='pit-v6-platform-v4-1';
const ASSETS=['/assets/ui.css','/assets/mobile.css','/assets/install.js','/assets/launch.js','/assets/offline.js','/assets/design.css','/assets/motion.js','/assets/shared.js','/assets/app.js','/assets/fonts/fonts.css','/assets/fonts/Onest-cyrillic.woff2','/assets/fonts/Onest-latin.woff2','/assets/fonts/AlumniSans-cyrillic.woff2','/assets/fonts/AlumniSans-latin.woff2','/assets/icons/icon-192.png','/assets/icons/icon-512.png','/assets/img/cars/eclass.webp','/assets/img/services/to.webp','/assets/img/services/diag.webp','/assets/img/services/brakes.webp','/assets/img/services/tire.webp','/assets/img/services/align.webp','/assets/img/services/susp.webp','/assets/img/services/ac.webp','/assets/img/services/elec.webp'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x.startsWith('pit-')&&x!==CACHE).map(x=>caches.delete(x)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==location.origin)return;
// Never cache private data, account pages, camera URLs or shared histories.
if(u.pathname.startsWith('/api/')||u.pathname.startsWith('/admin/')||u.pathname==='/platform'||u.pathname.startsWith('/history/')||u.pathname==='/qr')return;
if(u.pathname.startsWith('/assets/'))e.respondWith(fetch(e.request).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put(e.request,r.clone()));return r;}).catch(()=>caches.match(e.request)));
else if(e.request.mode==='navigate')e.respondWith(fetch(e.request).catch(()=>new Response("<!doctype html><html lang=\"ru\"><head><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>ПИТ · Нет соединения</title><link rel=\"stylesheet\" href=\"/assets/ui.css\"><link rel=\"stylesheet\" href=\"/assets/mobile.css\"><link rel=\"stylesheet\" href=\"/assets/design.css\"></head><body class=\"launch-body\"><main class=\"launch-shell\"><section class=\"boot-screen boot-error\"><div class=\"boot-brand\"><span class=\"boot-symbol\">П</span><b>ПИТ</b></div><div class=\"boot-visual\" aria-hidden=\"true\"><span class=\"boot-core\">П</span></div><div class=\"boot-copy\"><h1>Вы сейчас не в сети</h1><p>Для записи, просмотра заказов и сохранения изменений нужен интернет.</p></div><div class=\"boot-status\"><span class=\"boot-spinner\" aria-hidden=\"true\"></span><div><strong>Подключитесь к сети</strong><small>Мы не подтверждаем запись и не сохраняем изменения без ответа сервера.</small></div></div><button type=\"button\" class=\"primary wide\" id=\"offline-retry\">Попробовать снова</button></section></main><script src=\"/assets/offline.js\"></script></body></html>",{status:503,headers:{'Content-Type':'text/html; charset=utf-8'}})));
});