-- PIT v6. Dedicated private schema; existing public/auth tables are untouched.
CREATE SCHEMA IF NOT EXISTS pit;
CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA extensions;
SET LOCAL search_path = pit, extensions, pg_catalog;

CREATE TABLE pit.tenants (
 id text PRIMARY KEY, slug text UNIQUE NOT NULL CHECK (slug ~ '^[a-z0-9][a-z0-9-]{2,49}$'),
 owner_key text NOT NULL, config jsonb NOT NULL, revision integer NOT NULL DEFAULT 1 CHECK(revision>0)
);
CREATE TABLE pit.users (
 id text PRIMARY KEY, tenant text NOT NULL REFERENCES pit.tenants(id), email text NOT NULL,
 name text NOT NULL, phone text NOT NULL DEFAULT '', role text NOT NULL CHECK(role IN ('owner','master','client')),
 hash text NOT NULL, UNIQUE(tenant,email), UNIQUE(tenant,id)
);
CREATE TABLE pit.sessions (
 token text PRIMARY KEY CHECK(length(token)=64), user_id text NOT NULL REFERENCES pit.users(id), expires bigint NOT NULL
);
CREATE TABLE pit.vehicles (
 id text PRIMARY KEY, tenant text NOT NULL REFERENCES pit.tenants(id), user_id text NOT NULL,
 data jsonb NOT NULL, UNIQUE(tenant,id), FOREIGN KEY(tenant,user_id) REFERENCES pit.users(tenant,id)
);
CREATE TABLE pit.bookings (
 id text PRIMARY KEY, tenant text NOT NULL REFERENCES pit.tenants(id), user_id text NOT NULL,
 vehicle text NOT NULL, date text NOT NULL CHECK(date ~ '^\d{4}-\d{2}-\d{2}$'),
 start integer NOT NULL CHECK(start>=0 AND start<1440), duration integer NOT NULL CHECK(duration>0),
 post integer NOT NULL CHECK(post BETWEEN 1 AND 16), status text NOT NULL CHECK(status IN ('booked','working','completed','cancelled','waitlist')),
 data jsonb NOT NULL, UNIQUE(tenant,id), CHECK(start+duration<=1440),
 FOREIGN KEY(tenant,user_id) REFERENCES pit.users(tenant,id),
 FOREIGN KEY(tenant,vehicle) REFERENCES pit.vehicles(tenant,id),
 EXCLUDE USING gist (tenant WITH =, date WITH =, post WITH =, int4range(start,start+duration,'[)') WITH &&)
 WHERE (status IN ('booked','working'))
);
CREATE UNIQUE INDEX pit_one_working_per_post ON pit.bookings(tenant,post) WHERE status='working';
CREATE TABLE pit.notifications (
 id text PRIMARY KEY, tenant text NOT NULL REFERENCES pit.tenants(id), user_id text NOT NULL,
 message text NOT NULL, created text NOT NULL, is_read integer NOT NULL DEFAULT 0 CHECK(is_read IN(0,1)),
 FOREIGN KEY(tenant,user_id) REFERENCES pit.users(tenant,id)
);
CREATE TABLE pit.storage (
 tenant text NOT NULL REFERENCES pit.tenants(id), cell text NOT NULL CHECK(cell ~ '^[ABC]-(0[1-9]|1[0-9]|20)$'),
 vehicle text NOT NULL, data jsonb NOT NULL, PRIMARY KEY(tenant,cell), UNIQUE(tenant,vehicle),
 FOREIGN KEY(tenant,vehicle) REFERENCES pit.vehicles(tenant,id)
);
CREATE TABLE pit.shares (
 token text PRIMARY KEY CHECK(length(token)=48), tenant text NOT NULL REFERENCES pit.tenants(id),
 vehicle text NOT NULL, expires bigint NOT NULL, FOREIGN KEY(tenant,vehicle) REFERENCES pit.vehicles(tenant,id)
);
CREATE TABLE pit.audit (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant text NOT NULL REFERENCES pit.tenants(id),
 user_id text NOT NULL, action text NOT NULL, target text NOT NULL, created text NOT NULL,
 FOREIGN KEY(tenant,user_id) REFERENCES pit.users(tenant,id)
);
CREATE TABLE pit.photos (
 id text PRIMARY KEY, tenant text NOT NULL, booking text NOT NULL, object_path text UNIQUE NOT NULL,
 mime text NOT NULL CHECK(mime IN('image/jpeg','image/png','image/webp')),
 FOREIGN KEY(tenant,booking) REFERENCES pit.bookings(tenant,id)
);
CREATE TABLE pit.rate_limits (key text PRIMARY KEY, window_start timestamptz NOT NULL, hits integer NOT NULL);
CREATE INDEX pit_booking_schedule ON pit.bookings(tenant,date,status,start);
CREATE INDEX pit_vehicle_owner ON pit.vehicles(tenant,user_id);
CREATE INDEX pit_notes_owner ON pit.notifications(tenant,user_id,created DESC);
CREATE INDEX pit_session_expiry ON pit.sessions(expires);
CREATE INDEX pit_share_expiry ON pit.shares(expires);

-- No direct browser access: application authenticates its own HttpOnly sessions.
-- Database credentials are used only by the Vercel server, never by the frontend.
ALTER TABLE pit.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE pit.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE pit.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE pit.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pit.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE pit.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE pit.storage ENABLE ROW LEVEL SECURITY;
ALTER TABLE pit.shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE pit.audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE pit.photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE pit.rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON SCHEMA pit FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA pit FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA pit FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA pit REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA pit REVOKE ALL ON FUNCTIONS FROM PUBLIC, anon, authenticated;

CREATE FUNCTION pit.consume_rate_limit(p_key text) RETURNS integer
LANGUAGE sql SET search_path = '' AS $$
 INSERT INTO pit.rate_limits(key,window_start,hits) VALUES(p_key,now(),1)
 ON CONFLICT(key) DO UPDATE SET
 window_start=CASE WHEN pit.rate_limits.window_start<now()-interval '10 minutes' THEN now() ELSE pit.rate_limits.window_start END,
 hits=CASE WHEN pit.rate_limits.window_start<now()-interval '10 minutes' THEN 1 ELSE pit.rate_limits.hits+1 END
 RETURNING hits;
$$;
REVOKE ALL ON FUNCTION pit.consume_rate_limit(text) FROM PUBLIC, anon, authenticated;

-- Bucket is private; no public-read storage policies are introduced.
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
VALUES('pit-photos','pit-photos',false,3145728,ARRAY['image/jpeg','image/png','image/webp'])
ON CONFLICT(id) DO NOTHING;
