'use strict';
const E=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const STO=location.pathname.split('/')[2];
async function api(route,method='GET',data){const r=await fetch('/api/t/'+STO+'/'+route,{method,headers:method==='GET'?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data),credentials:'same-origin'});const b=await r.json();if(!r.ok){const err=new Error(b.error||'Ошибка сервера');err.status=r.status;throw err;}return b;}
const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n);
const time=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
const minutes=s=>Number(s.split(':')[0])*60+Number(s.split(':')[1]);
const dateStr=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',weekday:'short'});
const statusLabel={booked:'Записан',working:'В работе',completed:'Готово',cancelled:'Отменён',waitlist:'Лист ожидания'};
const formValues=f=>Object.fromEntries(new FormData(f));
function toast(message,error=false){const el=document.getElementById('toast');el.textContent=message;el.className='toast show'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',6500);}
function saveFile(filename,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function calendar(b,c){const stamp=(date,min)=>date.replaceAll('-','')+'T'+time(min).replace(':','')+'00';const safe=s=>String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');saveFile('pit-visit.ics',['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//PIT//Visits//RU','BEGIN:VEVENT','UID:'+b.id+'@pit','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').split('.')[0]+'Z','DTSTART:'+stamp(b.date,b.start),'DTEND:'+stamp(b.date,b.start+b.duration),'SUMMARY:'+safe(c.name+': '+b.data.items.map(i=>i.n).join(', ')),'LOCATION:'+safe(c.addr),'END:VEVENT','END:VCALENDAR',''].join('\r\n'),'text/calendar');}
async function shareText(text,url){if(navigator.share){try{await navigator.share({text,url});return;}catch(e){if(e.name==='AbortError')return;}}try{await navigator.clipboard.writeText(text+' '+url);toast('Ссылка скопирована');}catch{window.prompt('Скопируйте ссылку',text+' '+url);}}
const routeMap=c=>'https://yandex.ru/maps/?text='+encodeURIComponent(c.addr);
const field=(label,name,value='',type='text',extra='')=>`<label class="field"><span>${E(label)}</span><input name="${E(name)}" type="${E(type)}" value="${E(value)}" ${extra}></label>`;
const picture=(v,cls='')=>v.image?`<img class="${cls}" src="/assets/${E(v.image)}" alt="${E(v.brand+' '+v.model)}">`:`<div class="car-text ${cls}"><span>${E(v.brand)}</span><strong>${E(v.model)}</strong></div>`;
const empty=(title,body='')=>`<div class="empty"><h3>${E(title)}</h3><p>${E(body)}</p></div>`;
function loginHTML(admin=false,register=false){return `<div class="login card"><div class="eyebrow">ПИТ / ${E(STO)}</div><h1>${register?'Создать аккаунт':admin?'Вход владельца':'Добро пожаловать'}</h1><p class="muted">${admin?'Управление сервисом с компьютера':'Запись, автомобиль и связь с мастером'}</p><form id="auth-form" data-register="${register}">${register?field('Имя','name','','text','required maxlength="80"'):''}${field('Email','email','','email','required autocomplete="username"')}${field('Пароль','password','','password','required minlength="10" maxlength="128" autocomplete="'+(register?'new-password':'current-password')+'"')}${register?field('Телефон','phone','','tel'):''}<button class="primary" type="submit">${register?'Зарегистрироваться':'Войти'}</button><p id="form-error" class="error-text" role="alert"></p></form>${!admin?`<button class="link" data-action="${register?'login':'register'}">${register?'Уже есть аккаунт':'Создать аккаунт клиента'}</button>`:''}<small>Телефон — контактный, без фиктивного статуса «подтверждён».</small></div>`;}
async function photoData(file){if(!file)return null;if(file.size>3*1024*1024)throw Error('Фото не больше 3 МБ');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Выберите JPEG, PNG или WebP');return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
