'use strict';
const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pit-test-'));const port=3200+Math.floor(Math.random()*1000),base='http'+'://127.0.0.1:'+port;let server;const cookies={};let config,vehicleId,bookingId,share,masterId,slot;
async function req(who,route,method='GET',data,sto='garage-a'){const res=await fetch(base+'/api/t/'+sto+'/'+route,{method,headers:{...(method!=='GET'?{'Content-Type':'application/json'}:{}),...(cookies[who]?{Cookie:cookies[who]}:{})},body:data===undefined?undefined:JSON.stringify(data)});if(res.headers.get('set-cookie'))cookies[who]=res.headers.get('set-cookie').split(';')[0];return {status:res.status,data:await res.json()};}
function ok(r,s=200){assert.equal(r.status,s,JSON.stringify(r.data));return r.data;}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
before(async()=>{server=spawn(process.execPath,['server/server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,PORT:String(port),HOST:'127.0.0.1',DATA_DIR:dir,OWNER_EMAIL:'owner@pit.test',OWNER_PASSWORD:'Owner-Secret-2026',STO_SLUG:'garage-a',TZ:process.env.TZ||'Europe/Moscow'},stdio:['ignore','pipe','pipe']});let logs='';server.stderr.on('data',d=>logs+=d);for(let i=0;i<80;i++){await new Promise(r=>setTimeout(r,50));try{const r=await fetch(base+'/api/health');if(r.ok)return;}catch{}if(server.exitCode!==null)throw Error(logs);}throw Error('Startup timeout '+logs);});
after(async()=>{server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));fs.rmSync(dir,{recursive:true,force:true});});
test('01 anonymous cannot read private data',async()=>{assert.equal((await req('anon','vehicles')).status,401);assert.equal((await req('anon','config')).status,401);const c=ok(await req('anon','public')).config;assert.equal('cameraUrls'in c,false);});
test('02 owner login and real password rejection',async()=>{assert.equal((await req('bad','login','POST',{email:'owner@pit.test',password:'Wrong-Secret-2026'})).status,401);assert.equal(ok(await req('owner','login','POST',{email:'owner@pit.test',password:'Owner-Secret-2026'})).role,'owner');config=ok(await req('owner','config'));const c={...config.config,posts:1,open:0,close:1440};config=ok(await req('owner','config','PUT',{config:c,revision:config.revision}));});
test('03 optimistic settings revision prevents lost update',async()=>{assert.equal((await req('owner','config','PUT',{config:config.config,revision:config.revision-1})).status,409);});
test('04 register client, no owner permissions',async()=>{const u=ok(await req('client','register','POST',{email:'client@pit.test',password:'Client-Secret-2026',name:'Клиент',phone:'+79991112233'}));assert.equal(u.role,'client');assert.equal((await req('client','config')).status,403);assert.equal((await req('client','tenants','POST',{slug:'evil-sto',name:'bad'})).status,403);});
test('05 catalogue includes classic and modern cars',async()=>{const c=await (await fetch(base+'/api/catalog')).json();assert.equal(c.length,202);assert(c.some(x=>x.brand==='Lada'&&x.model.includes('2101')));assert(c.some(x=>x.model==='Golf II'));assert(c.some(x=>x.id==='monjaro'));});
test('06 create actual vehicle and manual custom model',async()=>{const v=ok(await req('client','vehicles','POST',{brand:'Volkswagen',model:'Golf II',year:1990,plate:'К482МО116',km:280000,engine:'1.8 MT',tire:'185/60 R14',oil:'по руководству',nextKm:290000}),201);vehicleId=v.id;assert.equal(v.year,1990);assert.equal(ok(await req('client','vehicles')).length,1);});
test('07 booking uses server price and real available capacity',async()=>{const q=ok(await req('client','slots','POST',{date:today(),services:['diag'],radius:16}));slot=q.slots.find(x=>x.available)?.start;assert(slot!==undefined,'Need free slot today');const r=ok(await req('client','bookings','POST',{vehicle:vehicleId,date:today(),start:slot,services:['diag'],radius:16,phone:'+79991112233',price:1,remind:true,wait:true}),201);bookingId=r.id;assert.equal(r.data.price,1500);assert.equal(r.post,1);assert.equal(ok(await req('client','bookings')).length,1);});
test('08 duplicate booking / overlapping capacity rejected',async()=>{assert.equal((await req('client','bookings','POST',{vehicle:vehicleId,date:today(),start:slot,services:['diag'],radius:16,phone:'+79991112233'})).status,409);});
test('09 other client cannot access vehicle or order',async()=>{ok(await req('other','register','POST',{email:'other@pit.test',password:'Other-Secret-2026',name:'Другой клиент'}));assert.equal(ok(await req('other','bookings')).length,0);assert.equal((await req('other','bookings/'+bookingId,'PATCH',{op:'chat',message:'bad'})).status,404);assert.equal((await req('other','vehicles/'+vehicleId,'PATCH',{brand:'A',model:'B',year:2000,km:0})).status,404);assert.equal((await req('client','bookings/'+bookingId,'PATCH',{op:'start'})).status,403);});
test('10 owner creates master, master blocked from owner settings',async()=>{masterId=ok(await req('owner','users','POST',{name:'Мастер',email:'master@pit.test',password:'Master-Secret-2026',role:'master'}),201).id;ok(await req('master','login','POST',{email:'master@pit.test',password:'Master-Secret-2026'}));assert.equal((await req('master','config')).status,403);assert.equal((await req('master','users')).status,403);});
test('11 start order, send real finding/photo',async()=>{assert.equal(ok(await req('master','bookings/'+bookingId,'PATCH',{op:'start'})).status,'working');const r=ok(await req('master','bookings/'+bookingId,'PATCH',{op:'finding',name:'Передние колодки',description:'Фото осмотра',price:3400,min:30,severity:'critical',photo:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a2b8AAAAASUVORK5CYII='}));assert.equal(r.data.findings.length,1);assert.equal((await req('master','bookings/'+bookingId,'PATCH',{op:'approve',finding:r.data.findings[0].id,accept:true})).status,403);});
test('12 client approval persists and increases price/duration exactly once',async()=>{const b=ok(await req('client','bookings/'+bookingId))[0],finding=b.data.findings[0].id;const r=ok(await req('client','bookings/'+bookingId,'PATCH',{op:'approve',finding,accept:true}));assert.equal(r.data.price,4900);assert.equal(r.duration,70);assert.equal((await req('client','bookings/'+bookingId,'PATCH',{op:'approve',finding,accept:true})).status,409);});
test('13 two-way chat stored on server',async()=>{ok(await req('client','bookings/'+bookingId,'PATCH',{op:'chat',message:'Когда готово?'}));const r=ok(await req('master','bookings/'+bookingId,'PATCH',{op:'chat',message:'Скоро закончим'}));assert.equal(r.data.chat.length,2);assert.equal(r.data.chat[0].role,'client');});
test('14 cannot close unfinished order; work progresses to completion',async()=>{assert.equal((await req('master','bookings/'+bookingId,'PATCH',{op:'complete'})).status,409);let b=ok(await req('master','bookings/'+bookingId))[0];for(const key of Object.keys(b.data.works)){ok(await req('master','bookings/'+bookingId,'PATCH',{op:'work',work:key}));ok(await req('master','bookings/'+bookingId,'PATCH',{op:'work',work:key}));}assert.equal(ok(await req('master','bookings/'+bookingId,'PATCH',{op:'complete'})).status,'completed');assert(ok(await req('client','notifications')).some(n=>n.message.includes('Машина готова')));});
test('15 storage accepts / double occupancy rejected / releases',async()=>{ok(await req('master','storage/B-14','PUT',{vehicle:vehicleId,count:4,season:'Летние',until:today(),note:'Бирка 123'}));assert.equal((await req('master','storage/B-14','PUT',{vehicle:vehicleId,count:4,season:'Летние',until:today()})).status,409);assert.equal(ok(await req('client','my-storage'))[0].cell,'B-14');assert.equal((await req('client','storage')).status,403);ok(await req('master','storage/B-14','DELETE',{}));assert.equal(ok(await req('client','my-storage')).length,0);});
test('16 history has real QR and no phone/plate; revoke works',async()=>{share=ok(await req('client','share/'+vehicleId,'POST',{}));const h=await (await fetch(base+'/api/shared/'+share.path.split('/')[2])).json();assert.equal(h.history.length,1);assert.equal(h.history[0].price,4900);assert.equal('plate'in h.vehicle,false);assert.equal('phone'in h.vehicle,false);const qr=await fetch(base+'/qr?path='+encodeURIComponent(share.path));assert.equal(qr.status,200);assert((await qr.text()).startsWith('<svg'));ok(await req('client','share/'+vehicleId,'DELETE',{}));assert.equal((await fetch(base+'/api/shared/'+share.path.split('/')[2])).status,404);});
test('17 second tenant isolated even for same owner account',async()=>{ok(await req('owner','tenants','POST',{name:'Второе СТО',slug:'garage-b'}),201);assert.equal((await req('client','vehicles','GET',undefined,'garage-b')).status,401);assert.equal((await req('owner','config','GET',undefined,'garage-b')).status,401);ok(await req('ownerB','login','POST',{email:'owner@pit.test',password:'Owner-Secret-2026'},'garage-b'));assert.equal(ok(await req('ownerB','vehicles','GET',undefined,'garage-b')).length,0);assert.equal((await req('ownerB','bookings/'+bookingId,'PATCH',{op:'chat',message:'bad'},'garage-b')).status,404);assert.equal(ok(await req('ownerB','config','GET',undefined,'garage-b')).config.name,'Второе СТО');});
test('18 export and audit are scoped, no password hashes',async()=>{const e=ok(await req('owner','export'));assert.equal(e.bookings.length,1);assert(e.users.every(u=>!('hash'in u)));assert(ok(await req('owner','audit')).some(a=>a.action==='booking.approve'));assert.equal((await req('master','export')).status,403);});
test('19 master password reset revokes old session',async()=>{ok(await req('owner','users/'+masterId,'PATCH',{password:'New-Master-2026'}));assert.equal((await req('master','me')).status,401);ok(await req('master','login','POST',{email:'master@pit.test',password:'New-Master-2026'}));});
test('20 CSRF origin and unsafe config rejected',async()=>{const r=await fetch(base+'/api/t/garage-a/config',{method:'PUT',headers:{'Content-Type':'application/json',Origin:'https://evil.test',Cookie:cookies.owner},body:'{}'});assert.equal(r.status,403);assert.equal((await req('owner','config','PUT',{config:{...config.config,accent:'javascript:alert(1)'},revision:config.revision})).status,400);assert.equal((await req('client','vehicles/'+vehicleId,'DELETE',{})).status,409);});
