"use strict";
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawn}=require('node:child_process');
const security=require('../server/security');
// Public RFC test vector, NEVER production enrollment material.
const fixture='GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ',bytes=security.decodeBase32(fixture);
const envKeys=['NODE_ENV','VERCEL','COOKIE_SECURE','PLATFORM_MFA_REQUIRED','PLATFORM_TOTP_SECRET'];
async function withEnv(values,fn){const old=Object.fromEntries(envKeys.map(k=>[k,process.env[k]]));try{for(const k of envKeys){if(values[k]===undefined)delete process.env[k];else process.env[k]=values[k];}return await fn();}finally{for(const k of envKeys){if(old[k]===undefined)delete process.env[k];else process.env[k]=old[k];}}}
test('S01 Secure cannot be disabled in production or Vercel',async()=>{for(const v of [{NODE_ENV:'production',COOKIE_SECURE:'false'},{VERCEL:'1',COOKIE_SECURE:'false'},{COOKIE_SECURE:'true'}])await withEnv(v,()=>assert.equal(security.secureCookie(),true));await withEnv({NODE_ENV:'test',COOKIE_SECURE:'false'},()=>assert.equal(security.secureCookie(),false));});
test('S02 production MFA is fail-closed, including false override',async()=>{await withEnv({NODE_ENV:'production',PLATFORM_MFA_REQUIRED:'false'},()=>{assert.equal(security.mfaRequired(),true);assert.throws(()=>security.mfaSettings());});await withEnv({VERCEL:'1',PLATFORM_TOTP_SECRET:'short'},()=>assert.throws(()=>security.mfaSettings()));});
test('S03 generated Base32 seeds are 160-bit and round-trip',()=>{const b=crypto.randomBytes(20),s=security.encodeBase32(b);assert.equal(s.length,32);assert.deepEqual(security.decodeBase32(s),b);assert.throws(()=>security.decodeBase32('not-valid!'));assert.throws(()=>security.decodeBase32('ABC'));});
test('S04 RFC6238 SHA1 test vectors and leading zeros',()=>{for(const [seconds,expected] of [[59,'287082'],[1111111109,'081804'],[1111111111,'050471'],[1234567890,'005924'],[2000000000,'279037'],[20000000000,'353130']])assert.equal(security.totp(bytes,Math.floor(seconds/30)),expected);});
test('S05 only six-digit current/adjacent TOTP counters accepted',()=>{const at=1700000000000,step=Math.floor(at/30000);for(const d of [-1,0,1])assert.equal(security.matchTotp(bytes,security.totp(bytes,step+d),at),step+d);assert.equal(security.matchTotp(bytes,security.totp(bytes,step-2),at),null);for(const c of ['12345','1234567','abcdef',123456,' 123456'])assert.equal(security.matchTotp(bytes,c,at),null);});
test('S06 spoofed proxy headers are ignored on direct connections',async()=>{await withEnv({NODE_ENV:'test'},()=>assert.equal(security.clientAddress({headers:{'x-vercel-forwarded-for':'8.8.8.8','x-forwarded-for':'1.1.1.1'},socket:{remoteAddress:'127.0.0.1'}}),'127.0.0.1'));await withEnv({VERCEL:'1'},()=>assert.equal(security.clientAddress({headers:{'x-vercel-forwarded-for':'8.8.8.8, 1.1.1.1'},socket:{remoteAddress:'127.0.0.1'}}),'8.8.8.8'));});
test('S07 account throttling spans different IPs and email case',async()=>{const l=security.createLimiter({testing:true});for(let i=0;i<8;i++)await l({headers:{},socket:{remoteAddress:'10.0.0.'+i}},i%2?' ADMIN@FIXTURE.TEST ':'admin@fixture.test','platform');await assert.rejects(()=>l({headers:{},socket:{remoteAddress:'10.0.1.1'}},'admin@fixture.test','platform'),e=>e.status===429);});
test('S08 tenant/account scopes do not cross-lock other companies',async()=>{const l=security.createLimiter({testing:true}),r={headers:{},socket:{remoteAddress:'127.0.0.1'}};for(let i=0;i<15;i++)await l(r,'same@fixture.test','tenant:a');await assert.rejects(()=>l(r,'same@fixture.test','tenant:a'),e=>e.status===429);await l(r,'same@fixture.test','tenant:b');await l(r,'different@fixture.test','tenant:a');});
test('S09 platform IP limit and Retry-After reset after window',async()=>{let at=0;const l=security.createLimiter({testing:true,clock:()=>at}),r={headers:{},socket:{remoteAddress:'127.0.0.1'}},h={};for(let i=0;i<20;i++)await l(r,undefined,'platform');await assert.rejects(()=>l(r,undefined,'platform',{setHeader:(k,v)=>h[k]=v}),e=>e.status===429);assert.equal(h['Retry-After'],'600');at=600001;await l(r,undefined,'platform');});
test('S10 production limits use persistent atomic DB counter and fail closed',async()=>{const keys=[],l=security.createLimiter({testing:false,get:async(q,k)=>{assert.equal(q,'SELECT pit.consume_rate_limit(?) AS hits');keys.push(k);return {hits:9};}});await assert.rejects(()=>l({headers:{},socket:{remoteAddress:'127.0.0.1'}},'admin@fixture.test','platform'),e=>e.status===429);assert.match(keys[0],/^[a-f0-9]{64}$/);assert.ok(!keys[0].includes('admin'));for(const hits of [undefined,null,'',0,-1,1.5,Infinity,true]){const broken=security.createLimiter({testing:false,get:async()=>({hits})});await assert.rejects(()=>broken({headers:{}}),e=>e.status===503);}});
test('S11 replay counters are monotonic and cannot be reused',()=>{const {DatabaseSync}=require('node:sqlite'),d=new DatabaseSync(':memory:');d.exec('CREATE TABLE platform_mfa_replay(credential TEXT PRIMARY KEY,last_step INTEGER,updated TEXT)');const q=d.prepare('INSERT INTO platform_mfa_replay AS used(credential,last_step,updated) VALUES(?,?,?) ON CONFLICT(credential) DO UPDATE SET last_step=excluded.last_step,updated=excluded.updated WHERE used.last_step<excluded.last_step');assert.equal(q.run('fixture',50,'now').changes,1);assert.equal(q.run('fixture',50,'now').changes,0);assert.equal(q.run('fixture',49,'now').changes,0);assert.equal(q.run('fixture',51,'now').changes,1);d.close();});
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pit-security-')),port=5100+Math.floor(Math.random()*250),base='http://127.0.0.1:'+port;let child,sessionCookie='',usedStep=null;
before(async()=>{child=spawn(process.execPath,['server/server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,NODE_ENV:'test',VERCEL:'',TEST_SQLITE_FILE:path.join(dir,'test.sqlite'),PORT:String(port),COOKIE_SECURE:'false',STO_SLUG:'security-auto',OWNER_EMAIL:'owner@security.test',OWNER_PASSWORD:'Security-Owner-Fixture-2026',PLATFORM_ADMIN_EMAIL:'admin@security.test',PLATFORM_ADMIN_PASSWORD:'short',PLATFORM_ADMIN_SECRET:'tiny',PLATFORM_TOTP_SECRET:fixture,PLATFORM_MFA_REQUIRED:'true',AUTH_RATE_SECRET:'public-security-test-only'},stdio:'ignore'});for(let i=0;i<100;i++){try{const r=await fetch(base+'/api/health');if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,30));}throw Error('Security test server did not start');});
after(async()=>{if(child&&!child.killed){child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));}fs.rmSync(dir,{recursive:true,force:true});});
async function login(data){const r=await fetch(base+'/api/platform/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'admin@security.test',password:'short',...data})});return {r,b:await r.json()};}
test('S12 public policy exposes only requirement, no enrollment secret',async()=>{const r=await fetch(base+'/api/platform/security'),b=await r.json();assert.deepEqual(b,{mfaRequired:true});assert.ok(!(JSON.stringify(b).includes(fixture)));});
test('S13 correct password without MFA does not issue a session',async()=>{const {r}=await login({});assert.equal(r.status,401);assert.equal(r.headers.get('set-cookie'),null);});
test('S14 invalid OTP denied, then short password plus valid MFA succeeds',async()=>{const wrong=await login({otp:'12345'});assert.equal(wrong.r.status,401);const step=Math.floor(Date.now()/30000)-1;usedStep=step;const {r,b}=await login({otp:security.totp(bytes,step)});assert.equal(r.status,200,JSON.stringify(b));sessionCookie=r.headers.get('set-cookie').split(';')[0];assert.match(sessionCookie,/pit_platform=/);assert.match(r.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.ok(!JSON.stringify(b).includes(fixture));const me=await fetch(base+'/api/platform/me',{headers:{Cookie:sessionCookie}});assert.equal(me.status,200);});
test('S15 used MFA counter is rejected without a new cookie',async()=>{const step=usedStep;const {r}=await login({otp:security.totp(bytes,step)});assert.equal(r.status,401);assert.equal(r.headers.get('set-cookie'),null);});
test('S19 concurrent use of a fresh code issues exactly one session',async()=>{const otp=security.totp(bytes,Math.floor(Date.now()/30000)),answers=await Promise.all([login({otp}),login({otp})]);assert.deepEqual(answers.map(x=>x.r.status).sort(),[200,401]);assert.equal(answers.filter(x=>x.r.headers.get('set-cookie')).length,1);});
test('S16 local tenant login still works and cross-site MFA login blocked',async()=>{const r=await fetch(base+'/api/t/security-auto/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'owner@security.test',password:'Security-Owner-Fixture-2026'})});assert.equal(r.status,200);const bad=await fetch(base+'/api/platform/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://unrelated.test'},body:JSON.stringify({email:'admin@security.test',password:'short',otp:'000000'})});assert.equal(bad.status,403);});
test('S17 migration protects replay table and SQLite/PG mapping agree',()=>{const sql=fs.readFileSync(path.resolve(__dirname,'../supabase/005_security.sql'),'utf8');assert.match(sql,/ENABLE ROW LEVEL SECURITY/);assert.match(sql,/REVOKE ALL.*PUBLIC,anon,authenticated/);assert.match(fs.readFileSync(path.resolve(__dirname,'../server/db.js'),'utf8'),/"platform_mfa_replay"/);});
test('S18 rotating MFA enrollment invalidates prior platform session',async()=>{await withEnv({NODE_ENV:'test',PLATFORM_MFA_REQUIRED:'true',PLATFORM_TOTP_SECRET:fixture},async()=>{const old={email:process.env.PLATFORM_ADMIN_EMAIL,password:process.env.PLATFORM_ADMIN_PASSWORD,key:process.env.PLATFORM_ADMIN_SECRET};try{process.env.PLATFORM_ADMIN_EMAIL='admin@security.test';process.env.PLATFORM_ADMIN_PASSWORD='short';process.env.PLATFORM_ADMIN_SECRET='tiny';const canonical=security.mfaSettings().canonical,fingerprint=crypto.createHmac('sha256','tiny').update('admin@security.test\0short\0mfa:'+canonical).digest('hex');const mod=require('../server/platform')({email:v=>v,fail:(status,msg)=>{throw Object.assign(Error(msg),{status})},get:async()=>({credential:fingerprint,expires:Date.now()+10000}),json:(_,v)=>v});const req={method:'GET',headers:{cookie:'pit_platform='+'a'.repeat(64)}},u=new URL('http://local/api/platform/me');assert.equal((await mod.route(req,{},u)).email,'admin@security.test');process.env.PLATFORM_TOTP_SECRET=security.encodeBase32(Buffer.alloc(20,3));await assert.rejects(()=>mod.route(req,{},u),e=>e.status===401);}finally{for(const [k,v] of [['PLATFORM_ADMIN_EMAIL',old.email],['PLATFORM_ADMIN_PASSWORD',old.password],['PLATFORM_ADMIN_SECRET',old.key]])if(v===undefined)delete process.env[k];else process.env[k]=v;}});});
