'use strict';
const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pit-workshop-')),port=4400+Math.floor(Math.random()*800),base='http://127.0.0.1:'+port,cookies={};let child,cfg,staff,client,vehicle,b1,b2,b3;
const day=(offset=0)=>new Date(Date.now()+offset*86400000).toISOString().slice(0,10);
async function req(who,route,method='GET',body,slug='workshop-a'){const r=await fetch(base+'/api/t/'+slug+'/'+route,{method,headers:{...(cookies[who]?{cookie:cookies[who]}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(r.headers.get('set-cookie'))cookies[who]=r.headers.get('set-cookie').split(';')[0];return {status:r.status,data:await r.json()};}
const ok=(x,status=200)=>{assert.equal(x.status,status,JSON.stringify(x.data));return x.data;};
async function mutate(b,input,who='master'){return req(who,'bookings/'+b.id,'PATCH',{...input,revision:b.data.revision||0});}
before(async()=>{child=spawn(process.execPath,['server/server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,NODE_ENV:'test',TEST_SQLITE_FILE:path.join(dir,'test.sqlite'),PORT:String(port),OWNER_EMAIL:'owner@workshop.test',OWNER_PASSWORD:'Workshop-Owner-2026',STO_SLUG:'workshop-a',COOKIE_SECURE:'false'},stdio:'ignore'});for(let i=0;i<80;i++){await new Promise(r=>setTimeout(r,50));try{if((await fetch(base+'/api/health')).ok)break;}catch{}}ok(await req('owner','login','POST',{email:'owner@workshop.test',password:'Workshop-Owner-2026'}));cfg=ok(await req('owner','config'));cfg=ok(await req('owner','config','PUT',{revision:cfg.revision,config:{...cfg.config,timezone:'UTC',posts:3,open:0,close:1440,days:[0,1,2,3,4,5,6]}}));staff=ok(await req('owner','users','POST',{name:'Мастер Антон',email:'master@workshop.test',password:'Workshop-Master-2026',role:'master'}),201);ok(await req('master','login','POST',{email:'master@workshop.test',password:'Workshop-Master-2026'}));client=ok(await req('client','register','POST',{name:'Клиент',email:'client@workshop.test',password:'Workshop-Client-2026',phone:'+70000000000'}));vehicle=ok(await req('client','vehicles','POST',{brand:'Mercedes-Benz',model:'E-Class',year:2020,plate:'А001АА',km:10000,engine:'2.0',tire:'R17'}),201);for(let i=0;i<2;i++){const v=i?ok(await req('client','vehicles','POST',{brand:'BMW',model:'320i',year:2020,plate:'А002АА',km:10000,engine:'2.0',tire:'R17'}),201):vehicle;const b=ok(await req('client','bookings','POST',{vehicle:v.id,date:day(1),start:90,services:['diag'],radius:17,phone:'+70000000000'}),201);if(i)b2=b;else b1=b;}});
after(async()=>{child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));fs.rmSync(dir,{recursive:true,force:true});});
test('W01 workshop is staff-only and does not expose account secrets',async()=>{assert.equal((await req('anon','workshop')).status,401);assert.equal((await req('client','workshop')).status,403);const w=ok(await req('master','workshop'));assert.equal(w.bookings.length,2);assert(w.staff.every(s=>Object.keys(s).sort().join(',')==='id,name,role'));assert(!('cameraUrls'in w.config));assert.equal((await req('master','users')).status,403);assert.equal((await req('master','config')).status,403);});
test('W02 assignment requires revision and a staff member of this STO',async()=>{assert.equal((await req('master','bookings/'+b1.id,'PATCH',{op:'assign',assigneeId:staff.id})).status,409);assert.equal((await mutate(b1,{op:'assign',assigneeId:client.id})).status,400);assert.equal((await mutate(b1,{op:'assign',assigneeId:staff.id},'client')).status,403);b1=ok(await mutate(b1,{op:'assign',assigneeId:staff.id}));assert.equal(b1.data.assigned.name,'Мастер Антон');assert.equal(b1.data.history.at(-1).op,'assign');});
test('W03 stale update does not overwrite assignment',async()=>{assert.equal((await req('owner','bookings/'+b1.id,'PATCH',{op:'assign',assigneeId:'',revision:b1.data.revision-1})).status,409);assert.equal(ok(await req('owner','bookings/'+b1.id))[0].data.assigned.id,staff.id);});
test('W04 occupied post is rejected; free post can be selected',async()=>{assert.equal((await mutate(b1,{op:'post',post:b2.post})).status,409);b1=ok(await mutate(b1,{op:'post',post:3}));assert.equal(b1.post,3);assert.equal(b1.data.history.at(-1).detail,'Пост 1 → 3');assert.equal((await mutate(b1,{op:'post',post:4})).status,400);});
test('W05 staff history is not sent to client; client can see responsible name',async()=>{const b=ok(await req('client','bookings/'+b1.id))[0];assert(!('history'in b.data));assert(!('historyTotal'in b.data));assert.equal(b.data.assigned.name,'Мастер Антон');assert.equal((await mutate(b1,{op:'start'})).status,409);});
test('W06 working order uses revisions and cannot be moved to another post',async()=>{const slots=ok(await req('client','slots','POST',{date:day(),services:['diag'],radius:17}));const slot=slots.slots.find(x=>x.available);assert(slot);b3=ok(await req('client','bookings','POST',{vehicle:vehicle.id,date:day(),start:slot.start,services:['diag'],radius:17,phone:'+70000000000'}),201);b3=ok(await mutate(b3,{op:'start'}));assert.equal((await mutate(b3,{op:'post',post:2})).status,409);const rev=b3.data.revision;b3=ok(await mutate(b3,{op:'work',work:'diag'}));assert.equal((await req('master','bookings/'+b3.id,'PATCH',{op:'work',work:'diag',revision:rev})).status,409);assert.equal(ok(await req('master','bookings/'+b3.id))[0].data.works.diag,'go');});
test('W07 pending approval blocks completion; only customer decides',async()=>{b3=ok(await mutate(b3,{op:'work',work:'diag'}));b3=ok(await mutate(b3,{op:'finding',name:'Замена крепления',description:'Осмотр',price:500,min:0}));assert.equal((await mutate(b3,{op:'complete'})).status,409);const id=b3.data.findings[0].id;assert.equal((await mutate(b3,{op:'approve',finding:id,accept:true})).status,403);const response=ok(await mutate(b3,{op:'approve',finding:id,accept:true},'client'));assert.equal(response.data.price,2000);b3=ok(await req('master','bookings/'+b3.id))[0];b3=ok(await mutate(b3,{op:'work',work:id}));b3=ok(await mutate(b3,{op:'work',work:id}));b3=ok(await mutate(b3,{op:'complete'}));assert.equal(b3.status,'completed');assert.equal(b3.data.history.at(-1).op,'complete');assert.equal((await mutate(b3,{op:'assign',assigneeId:staff.id})).status,409);});
test('W08 other branch cannot read or change a workshop order',async()=>{ok(await req('owner','tenants','POST',{name:'Другой филиал',slug:'workshop-b'}),201);assert.equal((await req('master','workshop','GET',undefined,'workshop-b')).status,401);ok(await req('ownerB','login','POST',{email:'owner@workshop.test',password:'Workshop-Owner-2026'},'workshop-b'));assert.equal(ok(await req('ownerB','workshop','GET',undefined,'workshop-b')).bookings.length,0);assert.equal((await req('ownerB','bookings/'+b1.id,'PATCH',{op:'assign',assigneeId:staff.id,revision:b1.data.revision},'workshop-b')).status,404);});
test('W09 legacy revision zero and bounded history are supported',()=>{const ws=require('../server/workshop');const data={};ws.revision(data,{revision:0},true);for(let i=0;i<205;i++)ws.record(data,{name:'Мастер',role:'master'},{op:'assign'},{},{});assert.equal(data.history.length,200);assert.equal(data.historyTotal,205);assert.equal(data.revision,205);assert(!('history'in ws.forRole(data,'client')));});
