'use strict';
// PIT v5: single-origin application, tenant-scoped SQLite persistence.
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite'); const QRCode=require('./qr');
const ROOT=path.resolve(__dirname,'..'),DATA=process.env.DATA_DIR||path.join(ROOT,'data');fs.mkdirSync(DATA,{recursive:true});
const db=new DatabaseSync(path.join(DATA,'pit.sqlite'));db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS tenants(id TEXT PRIMARY KEY,slug TEXT UNIQUE NOT NULL,owner_key TEXT NOT NULL,config TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,tenant TEXT NOT NULL REFERENCES tenants(id),email TEXT NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL DEFAULT '',role TEXT NOT NULL,hash TEXT NOT NULL,UNIQUE(tenant,email));
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS vehicles(id TEXT PRIMARY KEY,tenant TEXT NOT NULL REFERENCES tenants(id),user_id TEXT NOT NULL REFERENCES users(id),data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,tenant TEXT NOT NULL REFERENCES tenants(id),user_id TEXT NOT NULL REFERENCES users(id),vehicle TEXT NOT NULL REFERENCES vehicles(id),date TEXT NOT NULL,start INTEGER NOT NULL,duration INTEGER NOT NULL,post INTEGER NOT NULL,status TEXT NOT NULL,data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,tenant TEXT NOT NULL,user_id TEXT NOT NULL,message TEXT NOT NULL,created TEXT NOT NULL,is_read INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS storage(tenant TEXT NOT NULL,cell TEXT NOT NULL,vehicle TEXT NOT NULL REFERENCES vehicles(id),data TEXT NOT NULL,PRIMARY KEY(tenant,cell),UNIQUE(tenant,vehicle));
CREATE TABLE IF NOT EXISTS shares(token TEXT PRIMARY KEY,tenant TEXT NOT NULL,vehicle TEXT NOT NULL REFERENCES vehicles(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,tenant TEXT NOT NULL,user_id TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL,created TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS booking_schedule ON bookings(tenant,date,status,start);
CREATE INDEX IF NOT EXISTS vehicle_owner ON vehicles(tenant,user_id);
CREATE INDEX IF NOT EXISTS notes_owner ON notifications(tenant,user_id);
`);
const uid=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),J=JSON.parse;
const get=(q,...a)=>db.prepare(q).get(...a),all=(q,...a)=>db.prepare(q).all(...a),run=(q,...a)=>db.prepare(q).run(...a);
const catalogue=J(fs.readFileSync(path.join(__dirname,'catalog.json'),'utf8'));
const defaults={name:'Мой автосервис',addr:'',phone:'',accent:'#EC0618',posts:3,open:540,close:1260,days:[0,1,2,3,4,5,6],f:{camera:false,approve:true,lamp:true,history:true,waitlist:true,fixprice:true,chat:true,storage:true,plate:false,voice:true},cameraUrls:{},services:[{id:'to',n:'ТО и масло',price:2500,min:60},{id:'diag',n:'Диагностика',price:1500,min:40},{id:'brakes',n:'Тормоза',price:1800,min:60},{id:'susp',n:'Подвеска',price:1200,min:40},{id:'tire',n:'Шиномонтаж',price:1900,min:40,radius:true},{id:'align',n:'Развал-схождение',price:2200,min:50},{id:'ac',n:'Кондиционер',price:2800,min:50},{id:'elec',n:'Автоэлектрика',price:1500,min:60}]};
function hash(p){const s=crypto.randomBytes(16).toString('hex');return s+':'+crypto.scryptSync(p,s,64).toString('hex');}
function verify(p,h){const [s,v]=h.split(':');const b=crypto.scryptSync(p,s,64);return v.length===128&&crypto.timingSafeEqual(b,Buffer.from(v,'hex'));}
function fail(status,message){const e=new Error(message);e.status=status;throw e;}
function text(v,max=160){if(typeof v!=='string')fail(400,'Ожидался текст');return v.trim().slice(0,max);}
function integer(v,a,b){if(!Number.isInteger(v)||v<a||v>b)fail(400,'Число вне допустимого диапазона');return v;}
function password(v){if(typeof v!=='string'||v.length<10||v.length>128)fail(400,'Пароль: от 10 до 128 символов');return v;}
function email(v){v=text(v,160).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))fail(400,'Некорректный email');return v;}
function slug(v){v=text(v,50);if(!/^[a-z0-9][a-z0-9-]{2,49}$/.test(v))fail(400,'Код СТО: 3–50 латинских букв, цифр или дефисов');return v;}
function publicUser(u){return {id:u.id,email:u.email,name:u.name,phone:u.phone,role:u.role};}
function audit(u,a,t){run('INSERT INTO audit(tenant,user_id,action,target,created) VALUES(?,?,?,?,?)',u.tenant,u.id,a,t,now());}
function notify(u,message,tenant){run('INSERT INTO notifications VALUES(?,?,?,?,?,0)',uid(),tenant,u,message,now());}
function cfg(t){return J(t.config);}
function configValidate(c){const out={...defaults,name:text(c.name,80),addr:text(c.addr||'',200),phone:text(c.phone||'',40),accent:c.accent,posts:integer(c.posts,1,16),open:integer(c.open,0,1410),close:integer(c.close,30,1440)};if(!out.name||!/^#[0-9a-f]{6}$/i.test(out.accent)||out.close<=out.open)fail(400,'Проверьте название, цвет и часы');if(!Array.isArray(c.days)||!c.days.length)fail(400,'Выберите рабочие дни');out.days=[...new Set(c.days.map(v=>integer(v,0,6)))];out.f=Object.fromEntries(Object.keys(defaults.f).map(k=>[k,!!c.f?.[k]]));out.f.plate=false;out.cameraUrls={};for(const [k,v] of Object.entries(c.cameraUrls||{})){if(v){integer(+k,1,out.posts);const url=new URL(v);if(!['http:','https:'].includes(url.protocol)||url.username||url.password)fail(400,'Камера: HTTP(S) без пароля в URL');out.cameraUrls[k]=url.href;}}
if(!Array.isArray(c.services)||!c.services.length||c.services.length>50)fail(400,'Нужна хотя бы одна услуга');const ids=new Set();out.services=c.services.map(s=>{const id=text(s.id,40);if(!/^[a-z0-9_-]+$/.test(id)||ids.has(id))fail(400,'Коды услуг должны быть уникальными');ids.add(id);const n=text(s.n,80);if(!n)fail(400,'Название услуги обязательно');return {id,n,price:integer(s.price,0,10000000),min:integer(s.min,10,720),radius:!!s.radius};});return out;}
function transaction(f){db.exec('BEGIN IMMEDIATE');try{const out=f();db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}
function createTenant(code,conf,ownerKey,owner){const id=uid();run('INSERT INTO tenants(id,slug,owner_key,config) VALUES(?,?,?,?)',id,code,ownerKey,JSON.stringify(conf));run('INSERT INTO users(id,tenant,email,name,phone,role,hash) VALUES(?,?,?,?,?,?,?)',uid(),id,owner.email,owner.name,owner.phone||'','owner',owner.hash);return get('SELECT * FROM tenants WHERE id=?',id);}
if(!get('SELECT id FROM tenants LIMIT 1')){if(!process.env.OWNER_EMAIL||!process.env.OWNER_PASSWORD){console.error('Первый запуск: задайте OWNER_EMAIL и OWNER_PASSWORD (>=10 символов). См. README.md');process.exit(1);}transaction(()=>createTenant(slug(process.env.STO_SLUG||'first-sto'),{...defaults,name:process.env.STO_NAME||'Мой автосервис'},uid(),{email:email(process.env.OWNER_EMAIL),name:'Владелец',hash:hash(password(process.env.OWNER_PASSWORD))}));console.log('Создано первое СТО; постоянных демо-учётных записей нет.');}
function tenantBySlug(s){const t=get('SELECT * FROM tenants WHERE slug=?',s);if(!t)fail(404,'СТО не найдено');return t;}
function session(req){const token=(req.headers.cookie||'').match(/(?:^|;\s*)pit_session=([^;]+)/)?.[1];if(!token)return null;const s=get('SELECT user_id,expires FROM sessions WHERE token=?',crypto.createHash('sha256').update(token).digest('hex'));if(!s||s.expires<Date.now())return null;return get('SELECT * FROM users WHERE id=?',s.user_id);}
function auth(req,t,roles){const u=session(req);if(!u||u.tenant!==t.id)fail(401,'Войдите в это СТО');if(roles&&!roles.includes(u.role))fail(403,'Недостаточно прав');return u;}
function vehicle(u,id){const v=get('SELECT * FROM vehicles WHERE id=? AND tenant=?',id,u.tenant);if(!v||(u.role==='client'&&v.user_id!==u.id))fail(404,'Автомобиль не найден');return v;}
function booking(u,id){const b=get('SELECT * FROM bookings WHERE id=? AND tenant=?',id,u.tenant);if(!b||(u.role==='client'&&b.user_id!==u.id))fail(404,'Заказ не найден');return b;}
function expanded(b){const v=get('SELECT data FROM vehicles WHERE id=?',b.vehicle);const u=get('SELECT name,phone FROM users WHERE id=?',b.user_id);return {...b,data:J(b.data),vehicleData:J(v.data),client:u};}
function saveBooking(b,d,status=b.status){run('UPDATE bookings SET data=?,status=? WHERE id=? AND tenant=?',JSON.stringify(d),status,b.id,b.tenant);}
function checkDate(d){if(typeof d!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(d)||isNaN(Date.parse(d))||new Date(d).toISOString().slice(0,10)!==d)fail(400,'Неверная дата');const today=localDate();if(d<today||d>localDate(180))fail(400,'Запись возможна на ближайшие 180 дней');return d;}
function localDate(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function quote(c,body){if(!Array.isArray(body.services)||!body.services.length)fail(400,'Выберите услугу');const ids=[...new Set(body.services)];const ss=ids.map(id=>{const s=c.services.find(x=>x.id===id);if(!s)fail(400,'Услуга недоступна');return s;});const r=integer(body.radius||16,12,24);return {items:ss.map(s=>({...s,price:s.price+(s.radius?Math.max(0,r-14)*250:0),min:s.min+(s.radius?Math.max(0,r-14)*5:0)})),radius:r};}
function schedule(t,date,duration,exclude=null){const c=cfg(t),out=[];if(!c.days.includes(new Date(date+'T12:00:00').getDay()))return out;const list=all("SELECT * FROM bookings WHERE tenant=? AND date=? AND status NOT IN ('cancelled','completed','waitlist')",t.id,date).filter(b=>b.id!==exclude);const minute=new Date().getHours()*60+new Date().getMinutes();for(let s=c.open;s+duration<=c.close;s+=30){if(date===localDate()&&s<=minute)continue;const post=Array.from({length:c.posts},(_,i)=>i+1).find(p=>!list.some(b=>b.post===p&&s<b.start+b.duration&&s+duration>b.start));out.push({start:s,available:!!post,post:post||null});}return out;}
const rate=new Map();function limit(req){const key=req.socket.remoteAddress;const v=rate.get(key)||{time:Date.now(),n:0};if(Date.now()-v.time>600000){v.time=Date.now();v.n=0;}v.n++;rate.set(key,v);if(v.n>60)fail(429,'Слишком много попыток. Повторите позже');}
async function body(req){let s='';for await(const chunk of req){s+=chunk;if(Buffer.byteLength(s)>4*1024*1024)fail(413,'Файл слишком большой (до 3 МБ)');}try{return J(s||'{}');}catch{fail(400,'Некорректный JSON');}}
function json(res,v,status=200){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(v));}
function image(v){if(v==null)return null;if(typeof v!=='string'||v.length>4000000||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(v))fail(400,'Фото: JPEG, PNG или WebP до 3 МБ');return v;}
async function api(req,res,url){const p=url.pathname.split('/').filter(Boolean);if(p[1]==='health')return json(res,{ok:true});
if(p[1]==='shared'){const s=get('SELECT * FROM shares WHERE token=? AND expires>?',p[2],Date.now());if(!s)fail(404,'Ссылка истекла или отозвана');const v=get('SELECT data FROM vehicles WHERE id=? AND tenant=?',s.vehicle,s.tenant);const vd=J(v.data);return json(res,{vehicle:{brand:vd.brand,model:vd.model,year:vd.year},history:all("SELECT date,data FROM bookings WHERE tenant=? AND vehicle=? AND status='completed' ORDER BY date DESC",s.tenant,s.vehicle).map(b=>{const d=J(b.data);return {date:b.date,km:d.km,items:d.items.map(i=>i.n),price:d.price,findings:d.findings.filter(x=>x.decision==='approved').map(x=>({name:x.name,price:x.price}))};})});}
if(p[1]==='catalog')return json(res,catalogue);
if(p[1]!=='t'||!p[2])fail(404,'Маршрут не найден');const t=tenantBySlug(p[2]),c=cfg(t),action=p[3],method=req.method;let id=p[4];
if(action==='public'&&method==='GET'){const {cameraUrls,...conf}=c;return json(res,{slug:t.slug,config:conf});}
if(action==='login'||action==='register'){if(method!=='POST')fail(405,'Используйте POST');limit(req);const b=await body(req);const em=email(b.email),pw=password(b.password);let u=get('SELECT * FROM users WHERE tenant=? AND email=?',t.id,em);if(action==='register'){if(u)fail(409,'Email уже зарегистрирован');const name=text(b.name,80);if(!name)fail(400,'Укажите имя');run('INSERT INTO users VALUES(?,?,?,?,?,?,?)',uid(),t.id,em,name,text(b.phone||'',40),'client',hash(pw));u=get('SELECT * FROM users WHERE tenant=? AND email=?',t.id,em);}else if(!u||!verify(pw,u.hash))fail(401,'Неверный email или пароль');const tok=crypto.randomBytes(32).toString('hex');run('INSERT INTO sessions VALUES(?,?,?)',crypto.createHash('sha256').update(tok).digest('hex'),u.id,Date.now()+7*86400000);res.setHeader('Set-Cookie',`pit_session=${tok}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${process.env.COOKIE_SECURE==='true'?'; Secure':''}`);audit(u,'login',u.id);return json(res,publicUser(u));}
const u=auth(req,t);
if(action==='logout'&&method==='POST'){const tok=(req.headers.cookie||'').match(/pit_session=([^;]+)/)?.[1];if(tok)run('DELETE FROM sessions WHERE token=?',crypto.createHash('sha256').update(tok).digest('hex'));res.setHeader('Set-Cookie','pit_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,{ok:true});}
if(action==='me'){if(method==='GET')return json(res,publicUser(u));if(method==='PATCH'){const b=await body(req);const n=text(b.name,80);if(!n)fail(400,'Имя обязательно');run('UPDATE users SET name=?,phone=? WHERE id=?',n,text(b.phone||'',40),u.id);if(b.password){run('UPDATE users SET hash=? WHERE id=?',hash(password(b.password)),u.id);run('DELETE FROM sessions WHERE user_id=?',u.id);}return json(res,{ok:true});}}
if(action==='config'){auth(req,t,['owner']);if(method==='GET')return json(res,{config:c,revision:t.revision});if(method==='PUT'){const b=await body(req),conf=configValidate(b.config);transaction(()=>{const current=get('SELECT revision FROM tenants WHERE id=?',t.id);if(current.revision!==b.revision)fail(409,'Настройки изменились. Обновите страницу');if(all("SELECT post FROM bookings WHERE tenant=? AND status IN ('booked','working')",t.id).some(x=>x.post>conf.posts))fail(409,'Нельзя убрать пост с активными записями');run('UPDATE tenants SET config=?,revision=revision+1 WHERE id=?',JSON.stringify(conf),t.id);audit(u,'settings.update',t.id);});return json(res,{config:conf,revision:t.revision+1});}}
if(action==='tenants'){auth(req,t,['owner']);if(method==='GET')return json(res,all('SELECT slug,config FROM tenants WHERE owner_key=?',t.owner_key).map(x=>({slug:x.slug,name:cfg(x).name})));if(method==='POST'){const b=await body(req);if(get('SELECT id FROM tenants WHERE slug=?',slug(b.slug)))fail(409,'Код СТО занят');const nt=transaction(()=>createTenant(slug(b.slug),{...defaults,name:text(b.name,80)},t.owner_key,u));audit(u,'tenant.create',nt.id);return json(res,{slug:nt.slug},201);}}
if(action==='users'){auth(req,t,['owner']);if(method==='GET')return json(res,all('SELECT * FROM users WHERE tenant=? ORDER BY role,name',t.id).map(publicUser));if(method==='POST'){const b=await body(req);if(!['master','client'].includes(b.role))fail(400,'Роль: master или client');const em=email(b.email);if(get('SELECT id FROM users WHERE tenant=? AND email=?',t.id,em))fail(409,'Email занят');const newId=uid(),n=text(b.name,80);if(!n)fail(400,'Укажите имя');run('INSERT INTO users VALUES(?,?,?,?,?,?,?)',newId,t.id,em,n,text(b.phone||'',40),b.role,hash(password(b.password)));audit(u,'user.create',newId);return json(res,{id:newId},201);}if(method==='PATCH'){const b=await body(req),target=get('SELECT * FROM users WHERE id=? AND tenant=?',id,t.id);if(!target||target.role==='owner')fail(403,'Владелец не изменяется здесь');if(b.password){run('UPDATE users SET hash=? WHERE id=?',hash(password(b.password)),id);run('DELETE FROM sessions WHERE user_id=?',id);}if(b.role){if(!['master','client'].includes(b.role))fail(400,'Неверная роль');run('UPDATE users SET role=? WHERE id=?',b.role,id);run('DELETE FROM sessions WHERE user_id=?',id);}audit(u,'user.update',id);return json(res,{ok:true});}}
if(action==='vehicles'){if(method==='GET'){const vs=u.role==='client'?all('SELECT * FROM vehicles WHERE tenant=? AND user_id=?',t.id,u.id):all('SELECT * FROM vehicles WHERE tenant=?',t.id);return json(res,vs.map(v=>({id:v.id,userId:v.user_id,...J(v.data)})));}if(method==='POST'||method==='PATCH'){const b=await body(req);const cat=catalogue.find(x=>x.id===b.catalogId);const v={catalogId:cat?.id||null,brand:text(cat?.brand||b.brand,60),model:text(cat?.model||b.model,80),year:integer(b.year,1900,new Date().getFullYear()+1),plate:text(b.plate||'',20).toUpperCase(),km:integer(b.km||0,0,9999999),engine:text(b.engine||'',60),tire:text(b.tire||'',60),oil:text(b.oil||'',100),nextKm:b.nextKm==null?null:integer(b.nextKm,0,9999999),image:cat?.image||null};if(!v.brand||!v.model)fail(400,'Марка и модель обязательны');if(cat&&(v.year<cat.fromYear||v.year>cat.toYear))fail(400,'Год не соответствует выбранному поколению; используйте ручной ввод');if(method==='PATCH'){const prev=vehicle(u,id);if(u.role!=='client'&&u.role!=='owner')fail(403,'Редактирует клиент или владелец');run('UPDATE vehicles SET data=? WHERE id=? AND tenant=?',JSON.stringify(v),id,t.id);}else{let owner=u.id;if(u.role!=='client'&&b.userId){const client=get("SELECT id FROM users WHERE tenant=? AND id=? AND role='client'",t.id,b.userId);if(!client)fail(400,'Клиент не найден');owner=client.id;}id=uid();run('INSERT INTO vehicles VALUES(?,?,?,?)',id,t.id,owner,JSON.stringify(v));}audit(u,'vehicle.save',id);return json(res,{id,...v},method==='POST'?201:200);}if(method==='DELETE'){const v=vehicle(u,id);if(u.role==='master')fail(403,'Недостаточно прав');if(get('SELECT id FROM bookings WHERE vehicle=?',id)||get('SELECT cell FROM storage WHERE vehicle=?',id))fail(409,'У машины есть история или хранение; удаление запрещено');run('DELETE FROM shares WHERE vehicle=?',id);run('DELETE FROM vehicles WHERE id=?',id);audit(u,'vehicle.delete',id);return json(res,{ok:true});}}
if(action==='slots'&&method==='POST'){const b=await body(req),date=checkDate(b.date);if(b.exclude){const previous=booking(u,b.exclude);if(previous.status!=='booked')fail(409,'Перенос возможен до приёмки');return json(res,{date,duration:previous.duration,price:J(previous.data).price,slots:schedule(t,date,previous.duration,previous.id)});}const q=quote(c,b),duration=q.items.reduce((s,x)=>s+x.min,0);return json(res,{date,duration,price:q.items.reduce((s,x)=>s+x.price,0),slots:schedule(t,date,duration)});}
if(action==='bookings'){if(method==='GET'){let bs=u.role==='client'?all('SELECT * FROM bookings WHERE tenant=? AND user_id=? ORDER BY date DESC,start DESC',t.id,u.id):all('SELECT * FROM bookings WHERE tenant=? ORDER BY date DESC,start DESC',t.id);if(id)bs=bs.filter(b=>b.id===id);return json(res,bs.map(expanded));}
if(method==='POST'){const b=await body(req),v=vehicle(u,b.vehicle),q=quote(c,b),date=checkDate(b.date),duration=q.items.reduce((s,x)=>s+x.min,0),price=q.items.reduce((s,x)=>s+x.price,0),start=integer(b.start,0,1439),newId=uid();const data={...q,price,km:J(v.data).km,phone:text(b.phone||u.phone||'',40),note:text(b.note||'',1000),wait:!!b.wait,remind:!!b.remind,reminded:false,created:now(),findings:[],chat:[],works:Object.fromEntries(q.items.map(i=>[i.id,'wait']))};if(!data.phone)fail(400,'Укажите контактный телефон');transaction(()=>{const slot=schedule(t,date,duration).find(s=>s.start===start);if(!slot?.available)fail(409,'Окно уже занято. Выберите другое');run('INSERT INTO bookings VALUES(?,?,?,?,?,?,?,?,?,?)',newId,t.id,v.user_id,v.id,date,start,duration,slot.post,'booked',JSON.stringify(data));notify(v.user_id,'Запись подтверждена: '+date+' '+hm(start),t.id);audit(u,'booking.create',newId);});return json(res,expanded(booking(u,newId)),201);}
if(method==='PATCH'){const b=booking(u,id),input=await body(req);return json(res,transaction(()=>{const current=booking(u,id),d=J(current.data);if(input.op==='cancel'){if(!['booked','waitlist'].includes(current.status))fail(409,'Можно отменить только будущую запись');saveBooking(current,d,'cancelled');notify(current.user_id,'Запись отменена',t.id);for(const x of all("SELECT user_id,data,date,start FROM bookings WHERE tenant=? AND status='booked'",t.id).filter(x=>J(x.data).wait&&x.date+String(x.start).padStart(4,'0')>current.date+String(current.start).padStart(4,'0'))){notify(x.user_id,'Освободилось окно '+current.date+' '+hm(current.start)+'. Проверьте доступное время.',t.id);}}
else if(input.op==='reschedule'){if(current.status!=='booked')fail(409,'Перенос доступен до приёмки');const date=checkDate(input.date),start=integer(input.start,0,1439);const slot=schedule(t,date,current.duration,current.id).find(s=>s.start===start);if(!slot?.available)fail(409,'Окно уже занято');run('UPDATE bookings SET date=?,start=?,post=? WHERE id=?',date,start,slot.post,current.id);d.reminded=false;saveBooking(current,d);notify(current.user_id,'Запись перенесена: '+date+' '+hm(start),t.id);}
else if(input.op==='start'){auth(req,t,['master','owner']);if(current.status!=='booked')fail(409,'Заказ уже принят или закрыт');if(current.date>localDate())fail(409,'Приёмка только в день визита');if(get("SELECT id FROM bookings WHERE tenant=? AND post=? AND status='working'",t.id,current.post))fail(409,'Пост занят текущим заказом');d.started=now();saveBooking(current,d,'working');}
else if(input.op==='work'){auth(req,t,['master','owner']);if(current.status!=='working')fail(409,'Сначала примите автомобиль');if(!Object.hasOwn(d.works,input.work))fail(400,'Работа не найдена');const s=d.works[input.work];if(s==='done')fail(409,'Работа уже завершена');d.works[input.work]=s==='wait'?'go':'done';saveBooking(current,d);}
else if(input.op==='finding'){auth(req,t,['master','owner']);if(!c.f.approve)fail(403,'Согласование отключено');if(current.status!=='working')fail(409,'Находку добавляют в текущий заказ');const name=text(input.name,160);if(!name)fail(400,'Опишите находку');d.findings.push({id:uid(),name,description:text(input.description||'',1000),price:integer(input.price,0,10000000),min:integer(input.min,0,720),severity:['critical','soon','later'].includes(input.severity)?input.severity:'soon',photo:image(input.photo),decision:'pending',created:now()});saveBooking(current,d);notify(current.user_id,'Мастер отправил находку на согласование',t.id);}
else if(input.op==='approve'){if(u.role!=='client')fail(403,'Решение принимает клиент');if(current.status!=='working')fail(409,'Заказ закрыт');const f=d.findings.find(x=>x.id===input.finding);if(!f||f.decision!=='pending')fail(409,'Решение уже принято');f.decision=input.accept?'approved':'declined';f.decided=now();if(input.accept){const end=current.start+current.duration+f.min;if(end>c.close||get("SELECT id FROM bookings WHERE tenant=? AND date=? AND post=? AND id<>? AND status IN ('booked','working') AND start<? AND start+duration>?",t.id,current.date,current.post,current.id,end,current.start))fail(409,'Не хватает времени на посту для дополнительных работ. Мастер должен согласовать другое окно');d.price+=f.price;d.works[f.id]='wait';run('UPDATE bookings SET duration=duration+? WHERE id=?',f.min,current.id);}saveBooking(current,d);for(const m of all("SELECT id FROM users WHERE tenant=? AND role IN ('owner','master')",t.id))notify(m.id,'Клиент '+(input.accept?'согласовал':'отклонил')+' работу: '+f.name,t.id);}
else if(input.op==='chat'){if(!c.f.chat)fail(403,'Чат отключён');const message=text(input.message,2000);if(!message)fail(400,'Пустое сообщение');if(d.chat.length>=2000)fail(409,'Лимит сообщений заказа');d.chat.push({id:uid(),name:u.name,role:u.role,message,created:now()});saveBooking(current,d);if(u.role!=='client')notify(current.user_id,'Новое сообщение от мастера',t.id);else for(const m of all("SELECT id FROM users WHERE tenant=? AND role IN ('owner','master')",t.id))notify(m.id,'Новое сообщение от клиента',t.id);}
else if(input.op==='complete'){auth(req,t,['master','owner']);if(current.status!=='working')fail(409,'Заказ не в работе');if(Object.values(d.works).some(x=>x!=='done')||d.findings.some(x=>x.decision==='pending'))fail(409,'Завершите работы и дождитесь решения по находкам');d.finished=now();saveBooking(current,d,'completed');notify(current.user_id,'Машина готова. Можно забирать.',t.id);}
else fail(400,'Операция не поддерживается');audit(u,'booking.'+input.op,current.id);return expanded(booking(u,id));}));}}
if(action==='storage'){auth(req,t,['master','owner']);if(!c.f.storage)fail(403,'Хранение отключено');if(method==='GET')return json(res,all('SELECT * FROM storage WHERE tenant=?',t.id).map(s=>({...s,data:J(s.data),vehicleData:J(get('SELECT data FROM vehicles WHERE id=?',s.vehicle).data)})));if(method==='PUT'){const b=await body(req);if(!/^[ABC]-(0[1-9]|1[0-9]|20)$/.test(id))fail(400,'Ячейка A-01…C-20');const v=vehicle(u,b.vehicle);if(get('SELECT cell FROM storage WHERE tenant=? AND cell=?',t.id,id))fail(409,'Ячейка занята');const d={count:integer(b.count,1,8),season:text(b.season,40),until:text(b.until,10),note:text(b.note||'',200)};if(!/^\d{4}-\d{2}-\d{2}$/.test(d.until)||isNaN(Date.parse(d.until)))fail(400,'Укажите срок хранения');if(get('SELECT cell FROM storage WHERE tenant=? AND vehicle=?',t.id,v.id))fail(409,'Комплект этой машины уже на складе');run('INSERT INTO storage VALUES(?,?,?,?)',t.id,id,v.id,JSON.stringify(d));audit(u,'storage.accept',id);return json(res,{ok:true});}if(method==='DELETE'){const s=get('SELECT * FROM storage WHERE tenant=? AND cell=?',t.id,id);if(!s)fail(404,'Ячейка пуста');run('DELETE FROM storage WHERE tenant=? AND cell=?',t.id,id);audit(u,'storage.release',id);return json(res,{ok:true});}}
if(action==='my-storage'&&method==='GET')return json(res,all('SELECT s.cell,s.vehicle,s.data FROM storage s JOIN vehicles v ON v.id=s.vehicle WHERE s.tenant=? AND v.user_id=?',t.id,u.id).map(s=>({...s,data:J(s.data)})));
if(action==='notifications'){if(method==='GET')return json(res,all('SELECT * FROM notifications WHERE tenant=? AND user_id=? ORDER BY created DESC LIMIT 100',t.id,u.id));if(method==='POST'){run('UPDATE notifications SET is_read=1 WHERE tenant=? AND user_id=?',t.id,u.id);return json(res,{ok:true});}}
if(action==='share'){if(!c.f.history)fail(403,'История отключена');const v=vehicle(u,id);if(method==='POST'){const token=crypto.randomBytes(24).toString('hex'),expires=Date.now()+30*86400000;run('INSERT INTO shares VALUES(?,?,?,?)',token,t.id,v.id,expires);audit(u,'history.share',v.id);return json(res,{path:'/history/'+token,expires});}if(method==='DELETE'){run('DELETE FROM shares WHERE tenant=? AND vehicle=?',t.id,v.id);audit(u,'history.revoke',v.id);return json(res,{ok:true});}}
if(action==='camera'&&method==='GET'){const b=booking(u,id);if(!c.f.camera||!c.cameraUrls[b.post]||b.status!=='working')return json(res,{url:null,message:'Камера не подключена или заказ не в работе'});return json(res,{url:c.cameraUrls[b.post]});}
if(action==='audit'){auth(req,t,['owner']);return json(res,all('SELECT a.*,u.name FROM audit a JOIN users u ON u.id=a.user_id WHERE a.tenant=? ORDER BY a.id DESC LIMIT 100',t.id));}
if(action==='export'){auth(req,t,['owner']);return json(res,{exported:now(),config:c,vehicles:all('SELECT * FROM vehicles WHERE tenant=?',t.id).map(v=>({...v,data:J(v.data)})),bookings:all('SELECT * FROM bookings WHERE tenant=?',t.id).map(expanded),storage:all('SELECT * FROM storage WHERE tenant=?',t.id),users:all('SELECT * FROM users WHERE tenant=?',t.id).map(publicUser)});}
fail(404,'Маршрут не найден');}
const hm=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.webmanifest':'application/manifest+json','.woff2':'font/woff2','.png':'image/png','.webp':'image/webp','.svg':'image/svg+xml'};
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self'; media-src 'self' https: http: blob:; frame-src https: http:; object-src 'none'; base-uri 'self'; form-action 'self'");try{const url=new URL(req.url,'http://localhost');if(req.method!=='GET'&&req.method!=='HEAD'){if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`&&req.headers.origin!==`https://${req.headers.host}`)fail(403,'Запрос с другого сайта запрещён');if(req.headers['sec-fetch-site']==='cross-site')fail(403,'Запрос с другого сайта запрещён');if(!req.headers['content-type']?.startsWith('application/json'))fail(415,'Используйте JSON');}
if(url.pathname.startsWith('/api/'))return await api(req,res,url);
if(url.pathname==='/qr'){const target=url.searchParams.get('path');if(!/^\/history\/[a-f0-9]{48}$/.test(target||''))fail(400,'Некорректная ссылка');const origin=process.env.PUBLIC_ORIGIN||`http://${req.headers.host}`;let svg;try{svg=QRCode(origin+target);}catch(e){fail(400,e.message);}res.writeHead(200,{'Content-Type':'image/svg+xml','Cache-Control':'no-store'});return res.end(svg);}
if(url.pathname==='/') {res.writeHead(302,{Location:'/app/'+get('SELECT slug FROM tenants ORDER BY rowid LIMIT 1').slug});return res.end();}
let file;if(/^\/(app|admin)\/[a-z0-9-]+\/?$/.test(url.pathname)){tenantBySlug(url.pathname.split('/')[2]);file=path.join(ROOT,'pit',url.pathname.startsWith('/admin/')?'admin.html':'index.html');}else if(/^\/history\/[a-f0-9]{48}$/.test(url.pathname))file=path.join(ROOT,'pit/history.html');else if(url.pathname.startsWith('/assets/')){const rel=decodeURIComponent(url.pathname.slice(8));file=path.resolve(ROOT,'pit',rel);if(!file.startsWith(path.join(ROOT,'pit')+path.sep))fail(403,'Запрещено');}else fail(404,'Страница не найдена');if(!fs.existsSync(file)||!fs.statSync(file).isFile())fail(404,'Файл не найден');res.setHeader('Cache-Control','no-cache');res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');if(file.endsWith('sw.js'))res.setHeader('Service-Worker-Allowed','/');fs.createReadStream(file).pipe(res);
}catch(e){if(!e.status)console.error(e);if(!res.headersSent)json(res,{error:e.status?e.message:'Внутренняя ошибка сервера'},e.status||500);else res.end();}});
// Real in-app reminder, not a simulated push. External SMS/Telegram are not claimed.
const timer=setInterval(()=>{for(const b of all("SELECT * FROM bookings WHERE status='booked'")){const d=J(b.data);const at=new Date(b.date+'T'+hm(b.start)+':00').getTime();if(d.remind&&!d.reminded&&at-Date.now()<=7200000&&at>Date.now()){notify(b.user_id,'Напоминание: визит '+b.date+' '+hm(b.start),b.tenant);d.reminded=true;saveBooking(b,d);}}run('DELETE FROM sessions WHERE expires<?',Date.now());for(const [k,v] of rate)if(Date.now()-v.time>600000)rate.delete(k);},60000);timer.unref();
const port=+(process.env.PORT||3000);server.listen(port,process.env.HOST||'127.0.0.1',()=>console.log(`ПИТ: http://${process.env.HOST||'127.0.0.1'}:${port}`));function shutdown(){clearInterval(timer);server.close(()=>{db.close();process.exit(0);});}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
