PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS tenants(id TEXT PRIMARY KEY,slug TEXT UNIQUE NOT NULL,owner_key TEXT NOT NULL,config TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,tenant TEXT NOT NULL REFERENCES tenants(id),email TEXT NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL DEFAULT '',role TEXT NOT NULL,hash TEXT NOT NULL,UNIQUE(tenant,email));
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS vehicles(id TEXT PRIMARY KEY,tenant TEXT NOT NULL REFERENCES tenants(id),user_id TEXT NOT NULL REFERENCES users(id),data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,tenant TEXT NOT NULL REFERENCES tenants(id),user_id TEXT NOT NULL REFERENCES users(id),vehicle TEXT NOT NULL REFERENCES vehicles(id),date TEXT NOT NULL,start INTEGER NOT NULL,duration INTEGER NOT NULL,post INTEGER NOT NULL,status TEXT NOT NULL,data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,tenant TEXT NOT NULL,user_id TEXT NOT NULL,message TEXT NOT NULL,created TEXT NOT NULL,is_read INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS storage(tenant TEXT NOT NULL,cell TEXT NOT NULL,vehicle TEXT NOT NULL REFERENCES vehicles(id),data TEXT NOT NULL,PRIMARY KEY(tenant,cell),UNIQUE(tenant,vehicle));
CREATE TABLE IF NOT EXISTS shares(token TEXT PRIMARY KEY,tenant TEXT NOT NULL,vehicle TEXT NOT NULL REFERENCES vehicles(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,tenant TEXT NOT NULL,user_id TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL,created TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS booking_schedule ON bookings(tenant,date,status,start);
CREATE INDEX IF NOT EXISTS vehicle_owner ON vehicles(tenant,user_id);
CREATE INDEX IF NOT EXISTS notes_owner ON notifications(tenant,user_id);

CREATE TABLE IF NOT EXISTS photos(id TEXT PRIMARY KEY,tenant TEXT NOT NULL,booking TEXT NOT NULL,object_path TEXT NOT NULL,mime TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS companies(id TEXT PRIMARY KEY,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',access_until TEXT,created TEXT NOT NULL,updated TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS platform_sessions(token TEXT PRIMARY KEY,credential TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS platform_audit(id TEXT PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL,created TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS platform_mfa_replay(credential TEXT PRIMARY KEY,last_step INTEGER NOT NULL CHECK(last_step>=0),updated TEXT NOT NULL);
